### ISSUE TITLE
To-do list for Utility Man v3

### ISSUE THREAD

**Issue by NotTCA** [TCACodes/UtilityMan#1]
# To-do list
This is the official to-do list for Utility Man v3, I guess?

# Commands
- [ ] Command handler
- [ ] Moderation commands (kick, ban, ...)
- [ ] Dynamic help command with dropdown menu
- [ ] Ping command
- [ ] Say command [(as requested by g8speedy)](https://tca.is-from.space/r/Discord_B0U1qOEpwS.png)
# Features
- [ ] Welcomer and leaver
- [ ] Random status
- [ ] Reaction roles
